import { Prisma, PostType } from '@prisma/client';
import { prisma } from '../../config/db';
import { env } from '../../config/env';
import { keys, redis } from '../../config/redis';
import { badRequest, forbidden, notFound, tooManyRequests } from '../../utils/errors';
import { formatDistance } from '../../utils/geo';
import { clean, cleanOptional, isAllowedMediaUrl } from '../../utils/sanitize';
import { feedScore } from '../../utils/scoring';
import { notify } from '../notifications/notifications.service';

const authorSelect = {
  id: true,
  name: true,
  username: true,
  avatarUrl: true,
  city: true,
  trustTier: true,
  trustScore: true,
  interestTags: true,
} as const;

const MAX_IMAGES = 4;

/**
 * Public post shape. `dislikeCount` is dropped here and nowhere else, so a new
 * endpoint cannot leak it by forgetting to strip the field (spec §7, §11).
 */
function toPublicPost<T extends { dislikeCount?: number }>(post: T) {
  const { dislikeCount: _hidden, ...rest } = post;
  return rest;
}

// ────────────────────────────────────────────────────────── daily cap ──

/** Spec §7 — max 3 posts per rolling 24 h, 429 when exceeded. */
async function assertUnderDailyCap(authorId: string) {
  const [{ count }] = await prisma.$queryRaw<{ count: bigint }[]>(Prisma.sql`
    SELECT COUNT(*) AS count
    FROM "posts"
    WHERE "authorId" = ${authorId}::uuid
      AND status = 'PUBLISHED'
      AND "createdAt" > (NOW() AT TIME ZONE 'UTC') - INTERVAL '24 hours'
  `);

  const used = Number(count);
  if (used >= env.limits.postsPerDay) {
    throw tooManyRequests('Post limit reached for today', 'POST_LIMIT_REACHED');
  }

  // Mirrored into Redis so the compose screen can show remaining posts
  // without hitting Postgres.
  await redis.set(keys.postRateLimit(authorId), used + 1, 'EX', 86_400);
  return env.limits.postsPerDay - used - 1;
}

export async function remainingPostsToday(authorId: string) {
  const [{ count }] = await prisma.$queryRaw<{ count: bigint }[]>(Prisma.sql`
    SELECT COUNT(*) AS count
    FROM "posts"
    WHERE "authorId" = ${authorId}::uuid
      AND status = 'PUBLISHED'
      AND "createdAt" > (NOW() AT TIME ZONE 'UTC') - INTERVAL '24 hours'
  `);
  return {
    used: Number(count),
    limit: env.limits.postsPerDay,
    remaining: Math.max(env.limits.postsPerDay - Number(count), 0),
  };
}

// ──────────────────────────────────────────────────────────── create ──

export interface CreatePostInput {
  type: PostType;
  caption: string;
  mediaUrls?: string[];
  locationName?: string | null;
  lat?: number | null;
  lng?: number | null;
}

export async function createPost(authorId: string, input: CreatePostInput) {
  if (input.type === 'ACTIVITY_LOG') {
    throw badRequest(
      'Activity logs are generated automatically when an activity is completed',
      'ACTIVITY_LOG_AUTOGENERATED'
    );
  }

  const media = input.mediaUrls ?? [];
  if (media.length > MAX_IMAGES) {
    throw badRequest(`Attach at most ${MAX_IMAGES} images`);
  }
  if (media.some((url) => !isAllowedMediaUrl(url))) {
    throw badRequest(
      'Only jpeg, png, webp images and mp4 video are allowed',
      'INVALID_MEDIA'
    );
  }

  const remaining = await assertUnderDailyCap(authorId);

  const post = await prisma.post.create({
    data: {
      authorId,
      type: input.type,
      caption: clean(input.caption),
      mediaUrls: media,
      locationName: cleanOptional(input.locationName),
      lat: input.lat ?? null,
      lng: input.lng ?? null,
      status: 'PUBLISHED',
      publishedAt: new Date(),
    },
    include: { author: { select: authorSelect } },
  });

  return { post: toPublicPost(post), remainingToday: remaining };
}

/** Publish an auto-generated Activity Log draft (optional — spec §6). */
export async function publishDraft(
  postId: string,
  authorId: string,
  caption?: string,
  mediaUrls?: string[]
) {
  const draft = await prisma.post.findUnique({ where: { id: postId } });
  if (!draft) throw notFound('Post not found');
  if (draft.authorId !== authorId) throw forbidden('This draft is not yours');
  if (draft.status !== 'DRAFT') throw badRequest('This post is already published');

  if (mediaUrls?.some((url) => !isAllowedMediaUrl(url))) {
    throw badRequest('Unsupported media type', 'INVALID_MEDIA');
  }

  const post = await prisma.post.update({
    where: { id: postId },
    data: {
      status: 'PUBLISHED',
      publishedAt: new Date(),
      ...(caption ? { caption: clean(caption) } : {}),
      ...(mediaUrls ? { mediaUrls } : {}),
    },
    include: { author: { select: authorSelect } },
  });

  return toPublicPost(post);
}

export async function listDrafts(authorId: string) {
  const drafts = await prisma.post.findMany({
    where: { authorId, status: 'DRAFT' },
    orderBy: { createdAt: 'desc' },
    include: { author: { select: authorSelect } },
  });
  return drafts.map(toPublicPost);
}

export async function deletePost(postId: string, authorId: string) {
  const post = await prisma.post.findUnique({ where: { id: postId } });
  if (!post) throw notFound('Post not found');
  if (post.authorId !== authorId) throw forbidden('This post is not yours');

  await prisma.post.update({
    where: { id: postId },
    data: { status: 'REMOVED' },
  });
  return { deleted: true };
}

// ────────────────────────────────────────────────────────────── feed ──

interface FeedRow {
  id: string;
  distanceM: number | null;
  ageHours: number;
  sharedInterests: number;
  mutualActivities: number;
  hasActiveIntent: boolean;
}

/**
 * Home feed — posts from users near you, ranked by distance · recency ·
 * shared interests · mutual activity history (posts_profile_layer.svg).
 *
 * Popularity is deliberately absent: there are no follower counts and like
 * counts never enter the score.
 */
export async function feed(
  viewerId: string,
  params: { lat?: number; lng?: number; radiusKm: number; limit: number; offset: number }
) {
  const hasLocation = params.lat != null && params.lng != null;
  const radiusMeters = params.radiusKm * 1000;

  // Falls back to the author's own last-known point when a post carries no
  // location tag, so a Vibe Check still gets a distance badge.
  const viewerPoint = hasLocation
    ? Prisma.sql`ST_SetSRID(ST_MakePoint(${params.lng}, ${params.lat}), 4326)::geography`
    : Prisma.sql`NULL::geography`;

  const rows = await prisma.$queryRaw<FeedRow[]>(Prisma.sql`
    WITH viewer AS (
      SELECT "interestTags" FROM "users" WHERE id = ${viewerId}::uuid
    )
    SELECT
      p.id,
      CASE WHEN ${hasLocation}
        THEN ST_Distance(COALESCE(p.geom, a.geom), ${viewerPoint})
        ELSE NULL
      END AS "distanceM",
      EXTRACT(EPOCH FROM ((NOW() AT TIME ZONE 'UTC') - p."createdAt")) / 3600 AS "ageHours",
      (
        SELECT COUNT(*) FROM UNNEST(a."interestTags") t
        WHERE t = ANY(v."interestTags")
      )::int AS "sharedInterests",
      (
        SELECT COUNT(*) FROM "matches" m
        WHERE m.status = 'COMPLETED'
          AND ((m."makerId" = ${viewerId}::uuid AND m."companionId" = a.id)
            OR (m."companionId" = ${viewerId}::uuid AND m."makerId" = a.id))
      )::int AS "mutualActivities",
      EXISTS (
        SELECT 1 FROM "intents" i
        WHERE i."creatorId" = a.id AND i.status = 'ACTIVE' AND i."expiresAt" > (NOW() AT TIME ZONE 'UTC')
      ) AS "hasActiveIntent"
    FROM "posts" p
    JOIN "users" a ON a.id = p."authorId"
    CROSS JOIN viewer v
    WHERE p.status = 'PUBLISHED'
      AND a."deletedAt" IS NULL
      AND p."createdAt" > (NOW() AT TIME ZONE 'UTC') - INTERVAL '14 days'
      ${
        hasLocation
          ? Prisma.sql`AND (
              COALESCE(p.geom, a.geom) IS NULL
              OR ST_DWithin(COALESCE(p.geom, a.geom), ${viewerPoint}, ${radiusMeters})
            )`
          : Prisma.empty
      }
      AND p."authorId" NOT IN (SELECT "blockedId" FROM "blocks" WHERE "blockerId" = ${viewerId}::uuid)
      AND p."authorId" NOT IN (SELECT "blockerId" FROM "blocks" WHERE "blockedId" = ${viewerId}::uuid)
    ORDER BY p."createdAt" DESC
    LIMIT 400
  `);

  const ranked = rows
    .map((row) => ({
      id: row.id,
      score: feedScore({
        distanceM: row.distanceM,
        ageHours: Number(row.ageHours),
        sharedInterests: row.sharedInterests,
        mutualActivities: row.mutualActivities,
        hasActiveIntent: row.hasActiveIntent,
      }),
      meta: row,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(params.offset, params.offset + params.limit);

  if (!ranked.length) return { items: [], nextOffset: null };

  const posts = await hydrate(
    ranked.map((r) => r.id),
    viewerId
  );
  const byId = new Map(posts.map((p) => [p.id, p]));

  const items = ranked
    .map((r) => {
      const post = byId.get(r.id);
      if (!post) return null;
      return {
        ...post,
        distanceM: r.meta.distanceM != null ? Math.round(r.meta.distanceM) : null,
        distanceLabel: formatDistance(r.meta.distanceM),
        // "Intent live 🟢" badge.
        authorHasActiveIntent: r.meta.hasActiveIntent,
        sharedInterests: r.meta.sharedInterests,
      };
    })
    .filter(Boolean);

  return {
    items,
    nextOffset: rows.length > params.offset + params.limit
      ? params.offset + params.limit
      : null,
  };
}

/** Shared hydration: post + author + the viewer's own reaction. */
async function hydrate(ids: string[], viewerId: string) {
  const [posts, reactions] = await Promise.all([
    prisma.post.findMany({
      where: { id: { in: ids } },
      include: { author: { select: authorSelect } },
    }),
    prisma.postReaction.findMany({
      where: { postId: { in: ids }, userId: viewerId },
      select: { postId: true, type: true },
    }),
  ]);

  const myReaction = new Map(reactions.map((r) => [r.postId, r.type]));

  return posts.map((p) => ({
    ...toPublicPost(p),
    myReaction: myReaction.get(p.id) ?? null,
  }));
}

export async function getPost(postId: string, viewerId: string) {
  const post = await prisma.post.findUnique({
    where: { id: postId },
    include: { author: { select: authorSelect } },
  });
  if (!post || post.status === 'REMOVED') throw notFound('Post not found');

  const blocked = await prisma.block.findFirst({
    where: {
      OR: [
        { blockerId: viewerId, blockedId: post.authorId },
        { blockerId: post.authorId, blockedId: viewerId },
      ],
    },
  });
  if (blocked) throw notFound('Post not found');
  if (post.status === 'DRAFT' && post.authorId !== viewerId) {
    throw notFound('Post not found');
  }

  const [reaction, activeIntent] = await Promise.all([
    prisma.postReaction.findUnique({
      where: { postId_userId: { postId, userId: viewerId } },
      select: { type: true },
    }),
    prisma.intent.findFirst({
      where: {
        creatorId: post.authorId,
        status: 'ACTIVE',
        expiresAt: { gt: new Date() },
      },
      select: { id: true, title: true },
    }),
  ]);

  const isOwner = post.authorId === viewerId;

  return {
    ...toPublicPost(post),
    myReaction: reaction?.type ?? null,
    authorHasActiveIntent: Boolean(activeIntent),
    authorActiveIntent: activeIntent,
    isOwner,
    // Owner-only: the private dislike tally (spec §7).
    ...(isOwner ? { dislikeCount: post.dislikeCount } : {}),
  };
}

/** A user's own posts — the only place dislikeCount is exposed (spec §7). */
export async function myPosts(authorId: string, limit = 30, cursor?: string) {
  const rows = await prisma.post.findMany({
    where: { authorId, status: { in: ['PUBLISHED', 'DRAFT'] } },
    orderBy: { createdAt: 'desc' },
    take: limit + 1,
    ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
    include: { author: { select: authorSelect } },
  });

  const hasMore = rows.length > limit;
  return {
    items: hasMore ? rows.slice(0, limit) : rows, // dislikeCount intentionally kept
    nextCursor: hasMore ? rows[limit - 1].id : null,
  };
}

/** Another user's posts — the profile "Posts" tab. */
export async function userPosts(
  username: string,
  viewerId: string,
  limit = 30,
  cursor?: string
) {
  const author = await prisma.user.findUnique({
    where: { username: username.toLowerCase() },
    select: { id: true },
  });
  if (!author) throw notFound('Profile not found');

  if (author.id === viewerId) return myPosts(viewerId, limit, cursor);

  const blocked = await prisma.block.findFirst({
    where: {
      OR: [
        { blockerId: viewerId, blockedId: author.id },
        { blockerId: author.id, blockedId: viewerId },
      ],
    },
  });
  if (blocked) throw notFound('Profile not found');

  const rows = await prisma.post.findMany({
    where: { authorId: author.id, status: 'PUBLISHED' },
    orderBy: { createdAt: 'desc' },
    take: limit + 1,
    ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
    include: { author: { select: authorSelect } },
  });

  const hasMore = rows.length > limit;
  const items = hasMore ? rows.slice(0, limit) : rows;
  const hydrated = await hydrate(items.map((i) => i.id), viewerId);
  const byId = new Map(hydrated.map((h) => [h.id, h]));

  return {
    items: items.map((i) => byId.get(i.id)!).filter(Boolean),
    nextCursor: hasMore ? items[items.length - 1].id : null,
  };
}

// ───────────────────────────────────────────────────────── reactions ──

/**
 * Like / dislike. One reaction per user per post; tapping the same one again
 * clears it. Dislikes are counted but never publicly attributed or exposed.
 */
export async function react(
  postId: string,
  userId: string,
  type: 'LIKE' | 'DISLIKE'
) {
  const post = await prisma.post.findUnique({
    where: { id: postId },
    select: { id: true, authorId: true, status: true },
  });
  if (!post || post.status === 'REMOVED') throw notFound('Post not found');

  const existing = await prisma.postReaction.findUnique({
    where: { postId_userId: { postId, userId } },
  });

  let myReaction: 'LIKE' | 'DISLIKE' | null = type;

  await prisma.$transaction(async (tx) => {
    if (existing?.type === type) {
      // Toggle off.
      await tx.postReaction.delete({ where: { id: existing.id } });
      await tx.post.update({
        where: { id: postId },
        data:
          type === 'LIKE'
            ? { likeCount: { decrement: 1 } }
            : { dislikeCount: { decrement: 1 } },
      });
      myReaction = null;
      return;
    }

    if (existing) {
      // Switch sides: decrement the old counter, increment the new one.
      await tx.postReaction.update({ where: { id: existing.id }, data: { type } });
      await tx.post.update({
        where: { id: postId },
        data:
          type === 'LIKE'
            ? { likeCount: { increment: 1 }, dislikeCount: { decrement: 1 } }
            : { dislikeCount: { increment: 1 }, likeCount: { decrement: 1 } },
      });
      return;
    }

    await tx.postReaction.create({ data: { postId, userId, type } });
    await tx.post.update({
      where: { id: postId },
      data:
        type === 'LIKE'
          ? { likeCount: { increment: 1 } }
          : { dislikeCount: { increment: 1 } },
    });
  });

  if (type === 'DISLIKE' && myReaction === 'DISLIKE') {
    await maybeFlagForModeration(postId);
  }

  const fresh = await prisma.post.findUniqueOrThrow({
    where: { id: postId },
    select: { likeCount: true, commentCount: true },
  });

  return { ...fresh, myReaction };
}

/**
 * Spec §7 — >10 dislikes or >5 unique dislikers auto-flags a post for the
 * moderation queue. The post stays live until a human reviews it.
 */
async function maybeFlagForModeration(postId: string) {
  const [post, uniqueDislikers] = await Promise.all([
    prisma.post.findUnique({
      where: { id: postId },
      select: { dislikeCount: true, flaggedForModeration: true },
    }),
    prisma.postReaction.count({ where: { postId, type: 'DISLIKE' } }),
  ]);
  if (!post || post.flaggedForModeration) return;

  const byVolume = post.dislikeCount > env.limits.dislikeFlagCount;
  const byUniqueUsers = uniqueDislikers > env.limits.dislikeFlagUniqueUsers;
  if (!byVolume && !byUniqueUsers) return;

  await prisma.$transaction([
    prisma.post.update({
      where: { id: postId },
      data: { flaggedForModeration: true },
    }),
    prisma.moderationFlag.create({
      data: {
        postId,
        reason: byVolume
          ? `dislike_count ${post.dislikeCount} > ${env.limits.dislikeFlagCount}`
          : `unique dislikers ${uniqueDislikers} > ${env.limits.dislikeFlagUniqueUsers}`,
      },
    }),
  ]);
}

// ────────────────────────────────────────────────────────── comments ──

export async function addComment(
  postId: string,
  authorId: string,
  body: string,
  parentId?: string | null
) {
  const post = await prisma.post.findUnique({
    where: { id: postId },
    select: { id: true, authorId: true, status: true },
  });
  if (!post || post.status !== 'PUBLISHED') throw notFound('Post not found');

  if (parentId) {
    const parent = await prisma.comment.findUnique({
      where: { id: parentId },
      select: { postId: true, parentId: true },
    });
    if (!parent || parent.postId !== postId) throw notFound('Parent comment not found');
    // One level of nesting keeps the thread readable on a phone.
    if (parent.parentId) throw badRequest('Replies cannot be nested further');
  }

  const [comment] = await prisma.$transaction([
    prisma.comment.create({
      data: { postId, authorId, body: clean(body), parentId: parentId ?? null },
      include: { author: { select: authorSelect } },
    }),
    prisma.post.update({
      where: { id: postId },
      data: { commentCount: { increment: 1 } },
    }),
  ]);

  if (post.authorId !== authorId) {
    await notify({
      userId: post.authorId,
      type: 'SYSTEM',
      title: `${comment.author.name} commented`,
      body: comment.body.slice(0, 80),
      data: { postId, commentId: comment.id },
    });
  }

  return comment;
}

export async function listComments(postId: string, viewerId: string) {
  const comments = await prisma.comment.findMany({
    where: {
      postId,
      deletedAt: null,
      author: {
        AND: [
          { blocksReceived: { none: { blockerId: viewerId } } },
          { blocksMade: { none: { blockedId: viewerId } } },
        ],
      },
    },
    orderBy: { createdAt: 'asc' },
    include: { author: { select: authorSelect } },
  });

  // Threaded: top-level comments each carry their replies (spec §6).
  const roots = comments.filter((c) => !c.parentId);
  const repliesByParent = new Map<string, typeof comments>();
  for (const c of comments) {
    if (!c.parentId) continue;
    repliesByParent.set(c.parentId, [...(repliesByParent.get(c.parentId) ?? []), c]);
  }

  return roots.map((root) => ({
    ...root,
    replies: repliesByParent.get(root.id) ?? [],
  }));
}

export async function deleteComment(commentId: string, userId: string) {
  const comment = await prisma.comment.findUnique({
    where: { id: commentId },
    include: { post: { select: { authorId: true } } },
  });
  if (!comment) throw notFound('Comment not found');

  // The comment author or the post owner can remove it.
  if (comment.authorId !== userId && comment.post.authorId !== userId) {
    throw forbidden('You cannot delete this comment');
  }

  await prisma.$transaction([
    prisma.comment.update({
      where: { id: commentId },
      data: { deletedAt: new Date() },
    }),
    prisma.post.update({
      where: { id: comment.postId },
      data: { commentCount: { decrement: 1 } },
    }),
  ]);

  return { deleted: true };
}

/**
 * Share = an outbound deep link, never an in-app repost (§6 and
 * posts_profile_layer.svg both forbid reposting). The client hands this URL to
 * the native share sheet.
 */
export async function shareLink(postId: string, viewerId: string) {
  const post = await getPost(postId, viewerId);
  return {
    url: `https://daffodils.app/post/${postId}`,
    title: post.author.name,
    message: post.caption,
  };
}
